### ISSUE TITLE
A new folder is still created after an unsuccessful clone

### ISSUE THREAD

**Issue by kileymaki** [dmusican/Elegit#103]
For example, if you give a nonsense url a folder is created locally even though cloning fails.

**Comment by kileymaki** [comment]
Dave, a quick note: I think Graham may have fixed this with the most recent commit. I haven't confirmed it yet, though.

**Comment by dmusican** [comment]
Is this fixed? Should it closed?

**Comment by kileymaki** [comment]
This was indeed fixed
