### ISSUE TITLE
Upon opening, the commit trees scroll to the beginning instead of the most recent commit

### ISSUE THREAD

**Issue by kileymaki** [dmusican/Elegit#105]
Sometimes doesn't occur, but when it does I can't find any evidence of the Scrollpane being told to behave that way. Only explanation I can come up with is something to do with the unresponsive GUI while doing the initial loading. Tabling working on this for now until the loading is streamlined.

**Comment by dmusican** [comment]
Haven't seen in a while, fingers crossed it is fixed.

**Comment by dmusican** [comment]
Eric says keep clicking git status

**Comment by dmusican** [comment]
maybe after a push or a fetch

**Comment by connellyj** [comment]
Happened after I loaded a repo into Elegit

**Comment by connellyj** [comment]
Also happened after I cloned a repo

**Comment by connellyj** [comment]
Also when you fetch then merge, the window doesn't slide to be at the very front where they newly merged commits are

**Comment by erictwalker18** [comment]
Fixed via 0d0b4426fa5d1d484349a95141af3831895fda90
