### ISSUE TITLE
Elegit is slow and unresponsive while starting up

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#107]

**Comment by kileymaki** [comment]
I believe this is currently due to how the commit trees are created and a bug with java 8u40. The trees have to be generated on the application thread or errors get thrown. If my memory serves, this is fixed in 8u60, but I'd need refresh myself on the whole situation.

**Comment by kileymaki** [comment]
This has been resolved after updating our development version to 8u60. Initial setup is now handled in a separate thread from the application thread and the application is much more responsive on startup.
