### ISSUE TITLE
Can't close repository (or is really unclear how)

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#108]
I've got a repo open in Elegit that's causing some trouble, but I seem to have no way of closing it apart from switching to a different repo. If I'm trying to close it because I can't load other repos because of a bug, then I can't get another repo in, and I'm stuck... we need a way to close the repo.

This might make more sense if we also switch to a model where we can have multiple windows, one for each repo.

**Comment by kileymaki** [comment]
Closing a repo is not an option currently, so this would be an added feature.

**Comment by dmusican** [comment]
Test out lots of opening and closing

**Comment by dmusican** [comment]
Should this now be closed?

**Comment by shangdrk** [comment]
It's been fixed
