### ISSUE TITLE
Incorrect login doesn't give an error

### ISSUE THREAD

**Issue by mmantilla** [dmusican/Elegit#109]
Logging in with an incorrect username/password doesn't give any indication of an error, nor does it prevent the user from trying to open/clone a repo.

**Comment by dmusican** [comment]
Yes, this. Login requires complete rethinking: in git, you don't login as such; just prompt for a password when needed. Login button should go away.

**Comment by dmusican** [comment]
This should now be closed, shouldn't it?

**Comment by erictwalker18** [comment]
As far as I know it should be closed.
