### ISSUE TITLE
Menus aren't there

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#116]
Elegit needs a menu bar. Mac version has one by default, but there's nothing in it; Windows/Linux don't have one at all.

**Comment by grahamearley** [comment]
This should be a pretty easy add; we actually had this in there at one point this summer.

http://docs.oracle.com/javafx/2/api/javafx/scene/control/MenuBar.html

The #useSystemMenuBarProperty method works with the native Mac menu bar.

**Comment by dmusican** [comment]
Menus are there! But they overlap repository dropdown on Windows/Linux.

**Comment by dmusican** [comment]
Let's leave menus off the spring test; there's nothing in there currently.

**Comment by erictwalker18** [comment]
Menus are in and working, along with keyboard shortcuts, courtesy of Caleb
