### ISSUE TITLE
Rework persistent data storage

### ISSUE THREAD

**Issue by grahamearley** [dmusican/Elegit#120]
The current use of the `Preferences` library is a bit hacky (storing arrays and strings by converting them to byte streams).

Rework the data model to use XML (http://code.makery.ch/library/javafx-8-tutorial/part5/), and make the procedure clearer.

**Comment by dmusican** [comment]
This would be nice, maybe, though it will likely always be the lowest priority. Someone in the future who ends up deep in Preferences for some reason who is inspired to do something about this can do so.
