### ISSUE TITLE
Password kept when username is changed

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#130]
If you change your username via the username button, the previous saved password is kept and reused unless the user types in something new. When the username is changed, the password should be cleared out.

Further questions:

-  Should there be a username button at all? Rather, should it just be set in the authorize dialog that pops up?
-  Should username be repo specific? Each repo retains and remembers its own username?
 
This has been Eric's baby, so I dropped this in his lap, though we can reassign later if need be.

**Comment by erictwalker18** [comment]
Username button is gone, username can be edited in the authorization dialog, password is reset when a new username is entered, username is repo specific and each repo does remember its own username in a given session
