### ISSUE TITLE
Add console window showing git commands?

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#131]
Since one of the main purposes is to help learn about git, would it be reasonable to have a console-like window showing a history of commands? When you hit the drop box to change from one branch to another, showing "git checkout foo" might be really instructive.

**Comment by erictwalker18** [comment]
One possible idea: take over the notification window so users could see the past commands, then replace all notifications with the little white popups seen in the create/delete dialogue

**Comment by dmusican** [comment]
Agreed: dumping it for now into the notifications window would be a fine place to start.

**Comment by dmusican** [comment]
@ichiefboz got this started, but it's currently left unfinished in the "transcript" branch. He explained to me "The transcript branch only has a handful of Git commands posting to the transcript log file - the issue should remain open so that the GUI can still be implemented. I did get the “clear log” button from the menu bars working, so really all that needs to be done is (1) add more git commands and (2) display the window when the button gets clicked."

**Comment by mgorra** [comment]
Eva: GUI console display
Miriam: transcript

**Comment by dmusican** [comment]
Finished by @grenche and @mgorra. Thank you!

**Comment by dmusican** [comment]
Also thanks to @ichiefboz who started this work.
