### ISSUE TITLE
Linux menus are still a problem (Ubuntu/MATE)

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#133]
See attached.
![screenshot from 2016-02-24 17 17 13](https://cloud.githubusercontent.com/assets/695685/13304482/77605582-db1a-11e5-8d24-4995b98c6fff.png)

**Comment by dmusican** [comment]
I think the problem is due to the menus being added in Java code after the window has already been created via FXML. Mixing and matching these two doesn't make sense; they should be combined. That's not the only problem, though; some playing with that by me didn't solve the issue.

**Comment by dmusican** [comment]
We're going to take the menus out for the spring test. There's not much populated in them yet anyway.

**Comment by connellyj** [comment]
Fixed via f6896e69303cf80a3fe790a9c290158cddeaee3a
