### ISSUE TITLE
Git shallow clone as a way of viewing remote

### ISSUE THREAD

**Issue by shangdrk** [dmusican/Elegit#139]
Motivation: 
We want to support viewing remote repos in Elegit. One way of achieving this is to do a shallow clone of the remote repository, store it in a temp directory, and implement a simple directory tree viewer using javaFX to display it. However, at this point JGit doesn't support shallow clone.

Current Progress:
I explored the possibility of implementing shallow clone in JGit. It seems to be a complicated task. Basically to download all the objects we need, we can see what commit objects that the references in .git/refs/heads point to, find those commit objects and only download blob and tree objects that the commit objects specify, and leave out all the parents of those commits. This works fine until git creates something called pack to save disk space. For relatively large repos, git packs different versions of the same file (actually not necessarily the same file but that's the basic idea) into a pack object. Each time the user changes the file, git will store only the changes instead of an object containing all the contents. Due to this feature, a shallow clone becomes very complicated, because some objects we want to download might be in a packfile, and we need to figure out which pack it's in and what part of that pack is the version we want, etc.

**Comment by dmusican** [comment]
Turns out this is pretty challenging. We're going to walk away from this.
