### ISSUE TITLE
Write a test suite

### ISSUE THREAD

**Issue by grahamearley** [dmusican/Elegit#14]
Use JUnit

**Comment by dmusican** [comment]
Maybe JUnit, but let's try TestFX. (There's another called Jemmy if need be.) Create tests for some known bugs.

**Comment by grahamearley** [comment]
Here's an article with a good example for TestFX: http://www.oraclejavamagazine-digital.com/javamagazine_twitter/20150910?pg=17#pg17

**Comment by dmusican** [comment]
Tests are on the way. Doesn't need to be a bug of its own.
