### ISSUE TITLE
Git clone with ssh key

### ISSUE THREAD

**Issue by aelomio** [dmusican/Elegit#142]
Hi everyone,
I'm new to GIT and I'm tring to make à clone with an ssh key using NetBeans.

I got no error while cloning the projet from a Git repository, but when it's done and I create a branch to have all changes in the project, I can't view some files, like sql script, in the Projets window even if the files are present on the project folder.

Thanks

**Comment by dmusican** [comment]
I think you're confused as to where you're posting this... this is not help for Netbeans or Git in general, but rather a software project in-progress to make a new git client.
