### ISSUE TITLE
Set up web server to take POST requests

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#143]
We've got the new elegit.mathcs.carleton.edu server. It will eventually be elegit.org, but that's an easy change; regardless, start setting up the server to take POST requests for logging, both from Elegit as well as a command-line app.

**Comment by dmusican** [comment]
Likewise, get Elegit's logging to point to that server.

**Comment by dmusican** [comment]
Work with Kiley. HTML POST to get data into a database.

elegit.mathcs.carleton.edu; log in 
Kiley too

**Comment by dmusican** [comment]
Make secure and share code with Dave (point Dave to code)

**Comment by dmusican** [comment]
Use PHP. Eric will work with mtie to install on server and figure out a script for doing this.

**Comment by dmusican** [comment]
Continue working on database piece, get in version control via BitBucket, get us access.

**Comment by erictwalker18** [comment]
Done.
