### ISSUE TITLE
Complete lab for students to do

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#148]
Install GitHub git client. Get it figured out. Work with Kiley on coming up with a script of things to do to learn about Git.

Does GitHub have a "Hello world" for GitHub?

**Comment by dmusican** [comment]
Looks awesome!

- File bug reports for parts of lab that Elegit fails on.
- Develop similar version (and tweak this one as necessary) for GitHub Desktop.
- Does GHD do tags?

**Comment by dmusican** [comment]
Oh, in case this inspires any activities:

http://www.gotoquiz.com/phil_s_git_quiz

**Comment by dmusican** [comment]
Dave walk through, try out, and be inspired to write more quiz questions

**Comment by dmusican** [comment]
Walk through, update with more detail especially for GitHub Desktop, clarify...  or at least "note what needs to be clarified" (does this comment need clarification?)

**Comment by dmusican** [comment]
Walk through lab again with Elegit, but on a fork of a repo (pick one). Maybe this one?

https://github.com/TheElegitTeam/elegit_bug_reproduce

Fork the repo first, a few times, to make sure you don't lose track of the state. Using that repo, see if you can get a repeatable repetition of a bug.

**Comment by dmusican** [comment]
Get formatted or webbed up or something

**Comment by dmusican** [comment]
... for printing

**Comment by dmusican** [comment]
@dmusican Clarify locations of things in menus

**Comment by dmusican** [comment]
@dmusican Make last changes, fix GitHub Desktop to.... not have fetch, test it and make sure lab works as expected; also, make a test repo for each student, duplicate for everyone with teachers_pet

**Comment by dmusican** [comment]
And make paper copies, assign to students to groups, plan to tell students to show up

**Comment by erictwalker18** [comment]
User study happened!
