### ISSUE TITLE
Integrate interval commit loading to speed things up

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#158]
Startup time? Swirling when waiting? Time in general. You know what a responsive is supposed to look like, and we're much better than we were, but we need more.

Take these carefully and consult with us, design matters on this one in particular.

**Comment by erictwalker18** [comment]
Moving cells takes a lot of time, calculating their position is relatively quick. We can place just a few of the end commits first, then move the rest of them after it has loaded.

**Comment by erictwalker18** [comment]
Things have been sped up. All unit tests pass, will wait for another issue to show up
