### ISSUE TITLE
Tags with unpushed commites error happening on clean clone

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#160]
I added a unit test to make this happen: run the unit test testPushTaggingCheck in branch pushtag. It will fail because the method hasTagsWithUnpushedCommits returns true, even though it's a brand new clone. (I created this test because it was resulting in similar problems for me in the GUI.)

Let me know if you need help getting the unit test started -- it's one where you'll need to put your authentication info into a text file for it to read.

**Comment by dmusican** [comment]
Double check, but think through whether this is useful for user, or what should be done

**Comment by erictwalker18** [comment]
This is in fact a problem with the repo. The tag update1 points to a commit that was not pushed, so a clean clone of the repo with have a tag that points to an unpushed commit. In terms of what to do, I'll squash the notification, as people don't know what to do with it. Perhaps for later, we can include something in the menus that allows advanced stuff like that.

**Comment by erictwalker18** [comment]
Closing for now, can open it for making some cool features in the future.
