### ISSUE TITLE
Fresh cloned repo interrogates over and over to fetch.

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#171]
Fix that. Eric sees it all the time, so nag him if have trouble duplicating.

Do multiple branches play a role?

Write a unit test to fail due to bug.

**Comment by dmusican** [comment]
TURN IT OFF!!!!!!! (at least for the user test)

**Comment by shangdrk** [comment]
For now I commented out the code that shows "fetch new changes" notification.

**Comment by erictwalker18** [comment]
Fixed via 27b03437d2fe9bb929b3a7d20029aad5078698ea, was just wrongly named branches
