### ISSUE TITLE
Label checkout dropdown box as "checkout"

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#176]
One of the key goals with Elegit is to use standard Git terminology when possible / feasible. A number of students in our user study asked where "checkout" was. We should label the checkout dropdown box as "checkout". Perhaps it should even instead be a button that says "checkout" which then prompts for a branch. We should discuss precisely, but somehow, users should see the terminology.

**Comment by connellyj** [comment]
Labelled!
