### ISSUE TITLE
Lines overlap commits in the tree layout

### ISSUE THREAD

**Issue by erictwalker18** [dmusican/Elegit#180]
In large complicated repos like elegit, this can happen

**Comment by connellyj** [comment]
Also, sometimes the lines stretch diagonally from one commit to another
![screen shot 2016-06-14 at 12 59 41 pm](https://cloud.githubusercontent.com/assets/17103133/16053858/200b1638-3230-11e6-8b1a-1f3cf3b8ccb8.png)

**Comment by connellyj** [comment]
Fixed
