### ISSUE TITLE
Process for building releases for all 3 OS'es

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#187]
Can it be done on one OS for all three? ("cross-compiling", but it's Java which is platform independent bytecode, so is this doable in one place?)

Human script for installing releases to make sure they work, including cloning a repo or whatever

Eric: writeup what we have, then let Dave know and he'll/I'll take it from there.

**Comment by erictwalker18** [comment]
Short summary in Slack/google doc

**Comment by dmusican** [comment]
Can't be done on one machine for all three OSes. Can only build a native package for the OS that you're on. Sad, but true.

https://blogs.oracle.com/talkingjavadeployment/entry/native_packaging_for_javafx

We'll want to be consistent about where we do the build from.

**Comment by erictwalker18** [comment]
Version 0.5 has downloads for mac and windows in the release

**Comment by dmusican** [comment]
Eric finished all three OS'es, Eric is still working on Linux icon, Dave will continue to work on process for testing after building

**Comment by dmusican** [comment]
I've got a document called BuildTesting.md that's in the root directory of the repo. It's pretty sparse, but it's a start.
