### ISSUE TITLE
Clean up initialize, especially regarding code without a thread home

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#189]
We built this with a Model-View-Controller design in mind. Can you write a short description / vision / manifesto that explains how MVC is represented in Elegit? 

Some methods or code that initialize calls runs in the Application thread, and sometimes runs in worker threads. This is confusing, and cleaning this up to be more readable would be useful for maintainability going forward.

Perhaps use method naming to help make more clear where something should run?

**Comment by erictwalker18** [comment]
Calling it good enough for now. Might look at it later, but window pops up quickly and Julia cleaned up code well
