### ISSUE TITLE
Implement remote branch deletion

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#190]

**Comment by erictwalker18** [comment]
Jgit isn't doing what it's supposed to do on this, backlogging until jgit people respond to forum post

**Comment by erictwalker18** [comment]
Also fix branch creation updating branches

**Comment by erictwalker18** [comment]
Branches deleted/created locally are now updated correclty

**Comment by dmusican** [comment]
Try filing as a bug with JGit team.

**Comment by erictwalker18** [comment]
Turns out this is actually possible! Poorly documented though...

**Comment by dmusican** [comment]
NIce! Did they answer you, or did you find it yourself?

**Comment by erictwalker18** [comment]
I found some syntax in a bug report from 2012, then trial and errored the particular branch name syntax until I got it right...
