### ISSUE TITLE
Deleted commits aren't updated in the model when obtained a fetch or merge or whatever

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#194]
Fix it. Is this just about deleted commits? Or are the other ways the commit history could be changed that we don't get right? E.g. untracking a branch?

Within git status, check for changed commits. But git status is called a lot. Could slow things down. Not necessarily good. Hard. Solve.

(Clean up any code issues while you're at it.)

**Comment by erictwalker18** [comment]
Checkout box gets updated when a branch is deleted outside elegit, but other things are not updated

**Comment by connellyj** [comment]
When you delete a branch locally, it's commits don't get updated: they should get dotted out.

Also, when you create a new branch in elegit, it's head is not a traingle, but it should be

**Comment by erictwalker18** [comment]
Branch manager is updated when branches are deleted/added outside elegit

**Comment by erictwalker18** [comment]
Will take a big refactor. BIG.

**Comment by erictwalker18** [comment]
Fixed (with as few bugs as possible) via 5769641dc0d59ff04a3478d7d7603341bca47fd5
