### ISSUE TITLE
Strange behavior when loading an existing repository that's already loaded

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#196]
If you load an existing repository that's already loaded, it seems to load again (it's slow and takes time, looks like it's doing the same process), but you don't see it as a second repo in the dropdown list. I can't see any good reason why you should be able to load an existing repo twice. We should detect and prevent this with a reasonable error.

**Comment by connellyj** [comment]
Fixed via 9ee1a749625a20cca0a10fa1e71785b71294a4a1
