### ISSUE TITLE
Preserve current repo when removing repo shortcuts.

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#198]
When you click on the minus sign to remove repository shortcuts, that all works, etc, but when you're done, the repo that you previously had active doesn't resume. Instead, Elegit loads up the last repo in the list. It should stick with whatever repo you already had active.

(And, it shouldn't even reload it, presumably,)

**Comment by connellyj** [comment]
fixed via 580942d16f2ef9a1527a2f242faa4d7c94bba997
