### ISSUE TITLE
Track down Illegal Object Exceptions

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#203]
I was having a problem where whenever I loaded a local repo, it caused IllegalObjectExceptions. I can't trace this down anymore because Elegit won't start and I need to solve that problem first, but it's important that I try to duplicate this one and get it tracked better ASAP while I still remember what was going on.

**Comment by erictwalker18** [comment]
Likely due to local branches that weren't tracking a remote branch, see c698ef3de1360300b7be5c5729737f4d3c4ded9f

**Comment by dmusican** [comment]
We think Eric's amazing work has taken care of this. Will reopen if it comes back from the undead.
