### ISSUE TITLE
Branch name clarity

### ISSUE THREAD

**Issue by connellyj** [dmusican/Elegit#212]
Seeing the branch names is super important for understanding what's going on with git, but we don't do a great job of displaying them.

This shows particularly when you merge a branch into another branch in such a way that the reference to one branch just moves to a different commit (no new merge commit needed).

**Comment by connellyj** [comment]
Wait, is that what fast-forwarding is?

**Comment by erictwalker18** [comment]
Yep!

**Comment by connellyj** [comment]
Well I wanted this to also be a possible design thing, like maybe we could consider changing how we display branch names

**Comment by dmusican** [comment]
Also, two adjacent branch names run into each other, which makes things really confusing. I thought I had two branches merge together improperly, when it was really just the labels running together.

**Comment by erictwalker18** [comment]
Fixed via a01fd252d0e82fc4581fe5fab6c7dcc6f995e68d
