### ISSUE TITLE
New commit not recognized when fast-forwarding a branch

### ISSUE THREAD

**Issue by connellyj** [dmusican/Elegit#213]
![screen shot 2016-06-24 at 3 56 20 pm](https://cloud.githubusercontent.com/assets/17103133/16350502/9bd74056-3a24-11e6-9107-00c2e386a697.png)

In master, the rightmost commit should be dotted out.

**Comment by erictwalker18** [comment]
This begs the question, how do we draw the commit in remote-tracking? local_branch is being tracked remotely and the remote is tracking that commit, but fast_forward has to push that commit to the remote.

**Comment by erictwalker18** [comment]
Elegit does let you push, it gets confused as to where the remote branches are
