### ISSUE TITLE
Fix problem with GUI tests

### ISSUE THREAD

**Issue by erictwalker18** [dmusican/Elegit#225]
If you stop a GUI test in the middle of it, it will cause Elegit to fail when opening later

**Comment by dmusican** [comment]
Eric thinks it may have something to do with temp directories that persist, and Elegit tries to load them, or permissions, or something like that.

**Comment by dmusican** [comment]
I can't duplicate it. I've tried stopping the GUI tests in the middle of running, and I can't make the problem happen.  Sadly closing for now, but please reopen if problem found.
