### ISSUE TITLE
Rethink notification system

### ISSUE THREAD

**Issue by connellyj** [dmusican/Elegit#262]
Maybe do that thing that Intellij does where you pop up a little bubble at the bottom of the page? The notification pane is annoying

(Also needs to be changed in smaller windows like branchcheckout and merge windows)

**Comment by erictwalker18** [comment]
Moved it to the bottom, less annoying there, leaving for later

**Comment by erictwalker18** [comment]
Added via e6a57b831b29d0903213f46a52b06988277f4333
