### ISSUE TITLE
Main.sessionController calls in MergeWindowController

### ISSUE THREAD

**Issue by connellyj** [dmusican/Elegit#264]
There are Main.sessionController.<method> calls in handleMergeButton() (or in a method called by handleMergeButton()) that seem gross. How could this be better?

**Comment by connellyj** [comment]
Also static call to BranchCheckoutController from CreateDeleteBranchController

**Comment by erictwalker18** [comment]
Also static call to scrollto in treefx/CommitTreeScrollPanel
