### ISSUE TITLE
index.lock file issues - can't checkout

### ISSUE THREAD

**Issue by connellyj** [dmusican/Elegit#301]
I somehow got a .lock file put in my repo (something about a git crash?), but I can't checkout a different branch because of it.

I'm going to upload the directory with the repo in it to the google drive folder in case anyone needs it

**Comment by connellyj** [comment]
It's in a folder called LockBugRepo

**Comment by erictwalker18** [comment]
If you try to do this via command line, it says:
"fatal: Unable to create '.../index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue."

So Elegit not switching branches is correct, will update the error message.
