### ISSUE TITLE
SIGCSE paper

### ISSUE THREAD

**Issue by erictwalker18** [dmusican/Elegit#310]
Write the paper!

**Comment by erictwalker18** [comment]
Lit review done, see google drive

**Comment by erictwalker18** [comment]
First rough draft done

**Comment by erictwalker18** [comment]
Pictures to change:
-user study graph: take out title, make it go to black+white better, increase label font size
-include most recent UI changes in updated version of Elegit
-merge window icon?

**Comment by dmusican** [comment]
Redundant with #342.
