### ISSUE TITLE
Add posts to blog

### ISSUE THREAD

**Issue by erictwalker18** [dmusican/Elegit#311]
Write about:
-Experience writing Elegit
-Things we've learned about git
-Things we've learned about JavaFX/FXML
-Things we've learned about Java
-About the project
-Things we've learned about GUI design
-Things we've learned from the user study and people using an educational tool

**Comment by erictwalker18** [comment]
See Google doc for some post content, still working on where to put it

**Comment by dmusican** [comment]
https://pages.github.com/  ; Jekyll?

Julia will look at getting this set up.

**Comment by connellyj** [comment]
Jekyll is integrated - let's add some blog posts!

**Comment by connellyj** [comment]
We have two posts yay! The blog has begun.
