### ISSUE TITLE
Testing plan/release

### ISSUE THREAD

**Issue by erictwalker18** [dmusican/Elegit#313]
Figure out what the plan is for local testing or "worldwide" testing
-Local tests: people here, general use
-"worldwide": figure out a bug submission process/ incorporate it to Elegit, figure out opt in/out for logging

**Comment by erictwalker18** [comment]
"Worldwide" requires authentication to be ready

**Comment by erictwalker18** [comment]
First focus on a second user test, keep it similar to original for use in paper?

**Comment by dmusican** [comment]
Second user test is in progress.
