### ISSUE TITLE
Git status doesn't make sense

### ISSUE THREAD

**Issue by connellyj** [dmusican/Elegit#315]
When you fetch, the git status under the local repository says "behind by ** commits". But, the local repo isn't really behind, it has those commits, it's the working directory that's "behind". Right? This seems weird to me.

**Comment by erictwalker18** [comment]
Tricky one... the idea was to model this after command-line 'git status'
Behind/ahead really is whether refs/HEADS/<branch> is behind and/or ahead refs/remotes/<remote>/<branch>. Technically this is in the local repo, but I'm all ears on how this could be improved. I think the way we've separated them right now, working directory is just the current files and not commit states, which is what behind/ahead is tracking.

**Comment by erictwalker18** [comment]
I'm going to say Git status makes sense for now, can reopen if inspired to change the layout
