### ISSUE TITLE
Branch names off-screen

### ISSUE THREAD

**Issue by connellyj** [dmusican/Elegit#326]
When there are a lot of branches or branches with really long names, the labels go off screen and they're impossible to see. 

Also, when there are two layers of labels, the labels in the top label are taller than the other ones.

Also, the arrow button to expand the labels is still not great.

**Comment by erictwalker18** [comment]
Window width should dynamically resize (not sure why the scrollbar isn't working for this?)

**Comment by dmusican** [comment]
See #338 .
