### ISSUE TITLE
Merge window not sized correctly

### ISSUE THREAD

**Issue by connellyj** [dmusican/Elegit#327]
![screen shot 2016-08-08 at 9 54 28 am](https://cloud.githubusercontent.com/assets/17103133/17484103/259d3542-5d4e-11e6-9084-7ed35fd58d20.png)

The branch name is being cut off. Also should the "..." part be replaced with something else?

**Comment by erictwalker18** [comment]
Is this on opening the window or after resizing it?
Also I had "local branch..." in there before, but it made the window annoyingly wide, and the previous text says local branch head. Ideas on what it should be replaced with?

**Comment by connellyj** [comment]
This is on opening the window.

That's true, it's fine how it is then. Having local branch head above it and local branch below it would be a lot anyways.
