### ISSUE TITLE
Modify the Legend

### ISSUE THREAD

**Issue by connellyj** [dmusican/Elegit#328]
![screen shot 2016-08-08 at 9 58 22 am](https://cloud.githubusercontent.com/assets/17103133/17484280/b7e44e04-5d4e-11e6-84d2-de211daa18be.png)

I think there could be a little more explanation in the legend. Like "A commit in the local repository but not the remote repository". 

Should "A commit tracked locally and remotely" be "A commit in the local repository and the remote repository" to keep phrasing consistent?

Also, is saying "a commit not tracked locally" the same as saying that it's not represented in the working directory? Can we make that more explicit?

What exactly is a "normal" branch head?

**Comment by erictwalker18** [comment]
Phrasing could be more consistent. 

A 'commit not tracked locally' is not represented in the working directory, however, this is also true of every commit except HEAD. These remote commits are in fact stored in .git/objects/** even though they are part of remote branches, so saying they're not represented in the local repository isn't quite right either, it's really that nothing in .git/heads has a way of getting to them from by following parent pointers. Ideas on more specific language for this?

And "normal" is just bad, maybe a 'locally tracked branch head'?
