### ISSUE TITLE
Support git tags

### ISSUE THREAD

**Issue by grahamearley** [dmusican/Elegit#33]

**Comment by kileymaki** [comment]
I think adding a tag option to the context menu of a commit and putting tag info in the commit info section in the bottom right will be the steps for this in the fall.

**Comment by grahamearley** [comment]
Sounds good. I like the context menu idea.

**Comment by erictwalker18** [comment]
Tags can be added and deleted at will via the context menu. Annotated tags are supported in only the most basic capacity.

**Comment by erictwalker18** [comment]
Tags are interesting objects in Git. The main problem occurs when you:
-commit new changes
-create a tag for the new changes
-push the tag (but not the commit)
So what does this do? This will push the tag and new commit to the remote. However, this is not the same as pushing the new commit. The new commit can only be viewed by looking at the commit the tag references and its parents. Why is this difficult? Well, we have a tag that references a commit that we didn't parse, so we don't have a commit helper to point to for the tag.
Note: once you tag a commit, all previous commits will be included in this 'tag'
Options:
Do something Git doesn't do: parse the commits that the tag references like the rest of the commits (this is hard, probably not advisable)
List all tags in a separate place, as Github does. (Tricky, as we'd have to include a way to list the commit it references)
List tags that point to commits that aren't in the tree in a separate place and tags that point to commits that have been pushed in the commit info window.
Have the tag show up in the most recent commit that it applies to (perhaps confusing?)
Don't support tags that point to commits that haven't been pushed, but notify the user that they need to push the commit the tag references (easiest to implement)
What I'm doing- starting with 5

allow the user to make the tag if the commit hasn’t been pushed, but prevent the user from pushing that tag until the commit had been pushed
