### ISSUE TITLE
Branch labels not centered

### ISSUE THREAD

**Issue by connellyj** [dmusican/Elegit#338]
![screen shot 2016-08-09 at 8 41 21 am](https://cloud.githubusercontent.com/assets/17103133/17518327/269159c8-5e0d-11e6-914a-c6770e97641a.png)

When there's more than one layer of labels, the bottom layer centers on the commit instead of the top one. I think it should be the other way around, because when the menu is collapsed, it's unclear what the labels are attached to.

**Comment by dmusican** [comment]
Eric's goal is to triage -- easy or hard? Update Estimate accordingly?
