### ISSUE TITLE
Support .gitignore and adding files to it

### ISSUE THREAD

**Issue by grahamearley** [dmusican/Elegit#34]
Perhaps use a right-click context menu in the working tree directory panel.

**Comment by dmusican** [comment]
First propose what interface should look like.

**Comment by dmusican** [comment]
Have two different views of files. One is the current one that shows just status changes; the other shows all files and uses color/font/highlighting/smell/something to indicate status of file. Can then show ignored; can then also see .gitignore files and allow simple editing of them.

**Comment by dmusican** [comment]
What's the status of this one?

**Comment by kileymaki** [comment]
The 'All Files' view that includes ignored files is currently broken in some way. Once I've got that fixed again, we can think about how we want to handle editing the .gitignore

**Comment by kileymaki** [comment]
Adding files to the .gitignore works correctly from in Elegit now, unfortunately there is an issue with Git handling the .gitignore differently than I expected (see http://stackoverflow.com/questions/25436312/gitignore-not-working). Basically, when ignoring files that are already present, Git doesn't really ignore them.

**Comment by dmusican** [comment]
This can be closed now, can't it?

**Comment by kileymaki** [comment]
Yup, this is done.
