### ISSUE TITLE
Prepare end-of-summer user study

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#340]
Prepare questions for pre-test and post-test regarding knowledge of git. Leverage what we learned form last one regarding bad questions.

Prepare script (could be more minimal than last one, goal is to be quick and easy to make the script) to guide people through using it. This should perhaps be shorter than the last one, since that one took a lot of time. Then we can take notes as they do it.

Contact our other summer research friends and see when they can do this.

**Comment by connellyj** [comment]
Layla's group will do testing Thursday afternoon!

**Comment by connellyj** [comment]
Get repo from Dave!

**Comment by connellyj** [comment]
Removed some unnecessary language from the study and the part about merge conflicts since the pre/post test doesn't mention merge conflicts at all.

**Comment by connellyj** [comment]
Survey and tasks are in google docs, copies of the tasks are printed out and ready to go.
