### ISSUE TITLE
Set remote tracking branch

### ISSUE THREAD

**Issue by erictwalker18** [dmusican/Elegit#343]
Right now, if you push a branch that doesn't exist on the remote, it will create that new branch on the remote, but it won't set the current branch to track that

**Comment by connellyj** [comment]
For some reason, when you do a hard reset, the tracking is fixed.

I'm trying to find the JGit equivalent to push -u

**Comment by connellyj** [comment]
It looks like JGit doesn't support push -u, but I found a post about editing the config to set the upstream branch.

**Comment by erictwalker18** [comment]
Perhaps check out: http://download.eclipse.org/jgit/site/4.4.1.201607150455-r/apidocs/org/eclipse/jgit/api/CreateBranchCommand.SetupUpstreamMode.html?

**Comment by connellyj** [comment]
Yeah I've seen that, I was hoping to do it with some variation on the push command, but I don't think it's implemented. So I'll try this way

**Comment by erictwalker18** [comment]
Sounds good
