### ISSUE TITLE
Clean up adding and staging confusion

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#345]
If you have a file with a conflict, and a bunch of other files already staged, if you check all and click "Add", you get an error because you can't add files which are already staged. I guess that's reasonable, but it's really confusing; the interface shows checkboxes that I could check, but then it gives me an error.

Perhaps remove the checkboxes if it is already added? Needs some thought.

**Comment by erictwalker18** [comment]
Jgit doesn't support git.status().getAdded() (which is what should return these files)

**Comment by erictwalker18** [comment]
Nevermind, it's actually that Set doesn't support addAll, but the subclass HashSet does support addAll :)

**Comment by erictwalker18** [comment]
I'm thinking I'll remove checkboxes for staged files, perhaps needs to be reworked later.

**Comment by erictwalker18** [comment]
Added a separate notification for if you try to add when there are files checked that are staged. Didn't remove the checkboxes because you can still remove staged files. Perhaps we should have the remove and checkout buttons enabled in the all files view?
