### ISSUE TITLE
Lost upstream

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#346]
This mysterious bug has apparently happened twice now. Once to me. After a fetch, I see this at the command line:

```
$ git status
On branch master
Your branch is based on 'origin/master', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)
nothing to commit, working directory clean
```

A second fetch fixed it. In my case, it happened (I think) after doing some conflict resolution and another commit.

**Comment by connellyj** [comment]
Dave fixed it!
