### ISSUE TITLE
Merge pop up window has right side cut off

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#348]
![screen shot 2016-08-11 at 9 07 39 am](https://cloud.githubusercontent.com/assets/695685/17591310/37a8d1ae-5fa3-11e6-860a-182c26d5f3cf.png)

**Comment by connellyj** [comment]
Limit the branch name length in the dropdown and add tooltips to deal with crazy long branch names - similarly to how they're shortened in the local repository
