### ISSUE TITLE
Add successful notifications without popups

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#351]
When I push and fail because of a bad password, I get a notification that says it failed, which is good. But then when I try again, re-enter my username/password, and succeed, the notification bar still had the old failed message floating there, which is confusing. We should make it go away, or replace it with  a "succeeded" message. This is a general point that likely occurs in lots of places in the code, so we should think about this globally.

**Comment by erictwalker18** [comment]
Also consider having the latest notification fade after some amount of time (5 seconds?)

**Comment by connellyj** [comment]
The bubbles have an auto-hide on them, so they should go away whenever you click somewhere else, so when you do succeed they should already be gone.
