### ISSUE TITLE
Test on other operating systems

### ISSUE THREAD

**Issue by grahamearley** [dmusican/Elegit#36]
Linux, Windows

**Comment by kileymaki** [comment]
I've been running Elegit on my Windows desktop at home today, and so far it's been working pretty well. The only issue I've had is with a folder in the test repository that ended with a period, but that's not an issue with Elegit itself.

**Comment by dmusican** [comment]
Assigned to Dave for Linux

**Comment by dmusican** [comment]
We're all doing this all the TIME!
