### ISSUE TITLE
Updating current branch

### ISSUE THREAD

**Issue by erictwalker18** [dmusican/Elegit#366]
When creating a new branch and checking it out, the current branch doesn't update in ref labels, also true when you checkout a branch from the dialogue

**Comment by erictwalker18** [comment]
This should update in current branch, look into committreemodel's update(), and check if the current branch has changed

**Comment by erictwalker18** [comment]
This also causes errors when switching repos, checking out branches, etc.

**Comment by connellyj** [comment]
Cannot duplicate issue, will reopen if it reoccurs.
