### ISSUE TITLE
Menus for right-click features

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#378]
Hiding pushing tags behind a right click is too hard to find. (I couldn't find it until I was shown where it was, ditto for users playing with Elegit.) There are a number of other hidden right-click options. Is this time to finally work on menus? Should there be a push tags button? Should buttons with right clicks have dropdowns next to them? We should do something regarding push tags in particular.

**Comment by erictwalker18** [comment]
Menus- yes it's time. We're getting a lot of features only discoverable by right clicking.

Push tags button - not sure? Perhaps options next to it in the form of pictures of branches/tags (that are in the commit tree ref labels) so you can set the mode of push. This might get cluttered so another button might be the way to go

**Comment by connellyj** [comment]
Added via 1491570f886667d506e1302fe68632b0e36b0693
