### ISSUE TITLE
Buttons below commit info window should be less present

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#380]
Below the commit info window, there are two buttons: one for "Go to selected commit" and one for "Copy commit ID." These will likely both be rarely used, and so it may not make sense to add complexity to the main screen for rare features like this. A menu at the top right corner of the commit info box (perhaps add the ubiquitous three horizontal lines up there) might make more sense for including those capabilities.

**Comment by erictwalker18** [comment]
The icon is http://fontawesome.io/icon/bars/, look at other fontawesome usage to put it in

**Comment by dmusican** [comment]
I just found this old commit when cleaning up old branches. There's great work here we never merged in. I'm working on that now in branch redo-gui-changes.
