### ISSUE TITLE
Trying to checkout a remote-tracking branch gives wrong error.

### ISSUE THREAD

**Issue by connellyj** [dmusican/Elegit#401]
When you right click on a remote-tracking branch ref and click "checkout" it says: "Looks like that branch already exists locally!" which makes no sense. Perhaps the menu should say "Track" rather than "Checkout"?

**Comment by connellyj** [comment]
So checking out a remote branch is how you locally track a remote branch. Is "Checkout" the right thing to but in the menu then?

**Comment by connellyj** [comment]
Because this is what's really happening: `git checkout -b <branch> --track <remote>/<branch>` right?

**Comment by erictwalker18** [comment]
Yep! You make a new branch and tell it to track <remote>/<branch>. However, the --track isn't required

**Comment by connellyj** [comment]
So "Checkout" is the right thing for the context menu then? From a git perspective? Or do we need to say more about it?

**Comment by erictwalker18** [comment]
Perhaps make this menu a little more complicated. You can track remote branches with different names, and do all sorts of fun things, so maybe have a couple options, one to do a basic tracking, which should be labeled checkout, another for help about it and another to bring up a dialogue that has advanced checkout options.

This is advanced functionality so it probably could wait. For now, I think checkout is still the correct thing, as that's the Git command and we're trying not to lie to the users. One could list it as "checkout -b". There should be help though explaining that you make a new branch and set that branch to track that particular remote branch.

**Comment by connellyj** [comment]
I made an issue for advanced functionality, I'll leave it as is for now.
