### ISSUE TITLE
Fetching deleted remote refs

### ISSUE THREAD

**Issue by connellyj** [dmusican/Elegit#404]
I deleted a remote branch in one copy of a repo. In another copy, I couldn't delete the branch because it was already gone from the remote, and fetching didn't make it go away.

**Comment by erictwalker18** [comment]
This feature was taken out from fetch because it was causing bugs, careful when adding it.

See #346 and slack

**Comment by erictwalker18** [comment]
Nice approach using the config. Does the config change affect git usage outside elegit? If so maybe save what it was before the fetch and revert it to that.

**Comment by connellyj** [comment]
It adds a section to the config, then removes it at the end, which should be the same thing. I've tested it, and the added fetch section gets removed.

**Comment by erictwalker18** [comment]
Very cool! (I was mostly curious about it...)
