### ISSUE TITLE
setRemote() for push commands

### ISSUE THREAD

**Issue by connellyj** [dmusican/Elegit#406]
We need to setRemote() on all our push commands, otherwise they will always default to "origin" which is not always the case.

http://download.eclipse.org/jgit/site/4.4.1.201607150455-r/apidocs/index.html
default values

**Comment by connellyj** [comment]
These links never work... look for constant field values, it lists DEFAULT_REMOTE_NAME as origin

**Comment by erictwalker18** [comment]
To make the link work, open the link in a new tab: http://download.eclipse.org/jgit/site/4.4.1.201607150455-r/apidocs/constant-values.html#org.eclipse.jgit.lib.Constants.DEFAULT_REMOTE_NAME
