### ISSUE TITLE
Pushing new local branches

### ISSUE THREAD

**Issue by connellyj** [dmusican/Elegit#409]
Our push currently acts like a push -u, because it creates a remote-tracking branch and sets it as the upstream of any new local branches. Should push -u be menu option? Otherwise, we're kind of lying about what we're doing.

**Comment by connellyj** [comment]
Anytime you push, your upstream branches are going to change, and that might not be what people want, so I think it should be separated out. Right now, it's integrated into push though.

**Comment by erictwalker18** [comment]
I heartily agree with it being a different option. Some ideas would be to make the push button become a "push -u" button when you're on a branch with no corresponding remote tracking branch, or to have a popup window show up when you're pushing from a branch that isn't tracking a remote branch explaining the difference and asking the user which one to do. Either way, I think both should always be available, just one should be easier to get to than the other depending on the situation.

**Comment by connellyj** [comment]
Also, our "normal" push still creates a remote branch, it just doesn't track it. Git's push doesn't do that if a branch doesn't have an upstream branch.
