### ISSUE TITLE
Push authentication causes Pop ups to appear twice

### ISSUE THREAD

**Issue by connellyj** [dmusican/Elegit#413]
There are some pop up windows about untracked branches that show up, but the authentication makes them show up twice: once before and once after

**Comment by dmusican** [comment]
Fixed. I chose not to spin off a separate thread for the prepare stages of the operation. In principle, this might cause ugly slowdowns of the application thread, but this appears not to be a problem in practice. Perhaps if someone adds 1000 branches before pushing, this might be a problem. We an always revisit this if this is an issue.
