### ISSUE TITLE
Fix the mysterious ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by grahamearley** [dmusican/Elegit#42]
It comes up every now and then. From where?!

**Comment by kileymaki** [comment]
This bug remains elusive. If the stack trace shows something to do with Parent.updateCacheBounds, it may be a result of this bug: https://bugs.openjdk.java.net/browse/JDK-8096805. There was a previous fix for an index out of bounds error in this method (http://hg.openjdk.java.net/openjfx/8u-dev/rt/rev/eb251121a360), but that was last September.

It might have something to do with the animations and the fact that Cells use translateX/Y for their positioning, but I'm basing that on practically nothing.

**Comment by dmusican** [comment]
Nothing has been reported on this bug in a while. I"m going to close it for now until it comes back up.
