### ISSUE TITLE
Permission from users to log usage

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#440]
We need to make sure we ask permission from users the first time they start Elegit if it's ok to log usage data, and if not ok, to not do it. A popup when they start Elegit the first time would do it; store it in a user preference.

Secondarily, we should have a preferences screen where they can change this option. We'll undoubtedly have other preferences to add later.

**Comment by dmusican** [comment]
Eric suggests for now putting it in the menus, perhaps.

**Comment by dmusican** [comment]
Push to master, then make new builds so we can get people testing.

**Comment by erictwalker18** [comment]
Permissions added, built, and released.
