### ISSUE TITLE
Guessing Repository Name

### ISSUE THREAD

**Issue by twodee** [dmusican/Elegit#467]
When cloning a new remote repository, it'd be friendly to guess the repository name based on the remote URL. For example, if I paste in `https://github.com/yoozer/reepo` in the remote clone dialog, the repository name field is automatically set to `reepo`. But probably only if it's blank.

**Comment by dmusican** [comment]
Agreed, this would be nice to have!

**Comment by dmusican** [comment]
See [this comment](https://github.com/dmusican/Elegit/pull/497#issuecomment-294037414) regarding making this feature also work with ssh repos. While you're at it: that would make this functionality just complex enough that it should be factored out as a separate method, called from within the anonymous listener method. Giving it a descriptive name, something like `extractRepoName` would make the code more clear without even needing documentation to do it. That method could then also be unit tested.
