### ISSUE TITLE
Note that Java 8u40+ is required

### ISSUE THREAD

**Issue by joshuaeckroth** [dmusican/Elegit#484]
Specifically, required for some JavaFX features.

**Comment by dmusican** [comment]
Yep, that's right. We've do have a notice about this on the repo home page regarding setting up IntelliJ for development. Did you mean that you needed to upgrade Java in order to run the downloadable executables, or are you talking about development?

**Comment by joshuaeckroth** [comment]
I only tried building, not running the download. I must have missed the comment in the readme about 8u60+. In that respect, I consider this issue closed.
