### ISSUE TITLE
Fix Default Window Size on Launch and Window Resizing

### ISSUE THREAD

**Issue by MarthanielX** [dmusican/Elegit#486]
On my Windows 10 Laptop, the Elegit opens to a size slightly narrower but just as tall as the full screen and is positioned so that the top part of the program is beyond the top of the screen and the bottom partially obscured by the taskbar. Might as well open maximized by default. 

Also, when maximized, the branch checkout version buttons on the bottom of the window are mostly obscured by the taskbar when the taskbar is positioned at the bottom.

**Comment by MikeTheGreat** [comment]
Thank you for posting this - I was just about to file this bug myself :)
I'd like to add one more request to this: when one does resize the window the 'add' 'checkout files', etc buttons at the bottom stay put while the window shrinks. This means that as you make the window smaller (shorter, top-to-bottom) those buttons drop out of site and aren't accessible anymore.

**Comment by dmusican** [comment]
I just bumped up the priority of this, now that it's clearly affecting two people. Good news is that @MarthanielX is here at Carleton, so we can hopefully easily duplicate it.

**Comment by dmusican** [comment]
I'll further add to this bug that in when you resize the Elegit window, when you shrink the window by more than a bit, the tree windows etc don't resize as well as they should.

@MikeTheGreat and @erictwalker18 : what resolution are you running at?

**Comment by dmusican** [comment]
@MikeTheGreat and @erictwalker18 : nevermind. I've duplicated the bug in a Windows VM. It's kind of cool because I can set the desktop to a variety of sizes.

**Comment by dmusican** [comment]
Fixed and merged into master. @MikeTheGreat : I haven't created a new build yet, but feel free to snag and build yourself if you want to see it resizing properly now. (And of course, speak up if something isn't looking right). I'm aware of one or two other minor glitches, but the current master should hopefully be a big improvement regarding starting size.
