### ISSUE TITLE
Add somewhere a link to the cascadia.edu Elegit tutorial

### ISSUE THREAD

**Issue by miniwark** [dmusican/Elegit#526]
This link is the only Elegit tutorial i have find:
https://faculty.cascadia.edu/mpanitz/Courses/BIT142/Lessons/Lesson_110_Git/Elegit/Install_Basics.html

It's not perfect (there are GitKraken stuff mixed with it), it's hard to find too
but it's a good read to start working with Elegit.

**Comment by dmusican** [comment]
Thanks so much for this link; I've added it to the README.md that appears right up front.
