### ISSUE TITLE
Add a test to count methods in TestFX tests

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#585]
TestFX works poorly when there is more than one test in a class, and the errors are unclear. 

https://github.com/TestFX/TestFX/issues/173

Write a test to count the number of methods in our TestFX tests and verify that there is only one in each. That way, if one of our developers goofs and puts in too many, it will get caught with a clearer error.

**Comment by kevinamick** [comment]
Hey there @dmusican,

Please forgive me for my ignorance, this is my first open source contribution attempt...

I'm trying to find where the TestFX tests are located and am not seeing a reference to them anywhere? Just seeing the dependency for testfx in the pom.

Could you point me in the right direction?

**Comment by dmusican** [comment]
@kevinamick: switch over to the develop branch; you'll find them in there:

https://github.com/dmusican/Elegit/tree/develop/src/test/java/elegitfx

**Comment by kevinamick** [comment]
Great thanks! I believe I've got something to the effect of what you're looking for. https://github.com/dmusican/Elegit/pull/587

Although it is failing on the TreeLayoutFXTest which has 2 tests. Am I missing something here?

**Comment by dmusican** [comment]
See comments in pull request; all is now merged in. Many thanks.
