### ISSUE TITLE
Lack of error message when trying to commit when there are unmerged files

### ISSUE THREAD

**Issue by grenche** [dmusican/Elegit#613]
When you try to commit a file (even one without the conflict) when there exists a file with a conflict that has not been dealt with, a notification to the user should be shown. This isn't allowed when using the command line either, so we need a clear error to the user.

Also, an error is thrown in CommitController line 145, but not caught/dealt with when this happens.

To replicate, create some kind of conflict so the repo state is MERGING and then attempt to make a commit.

**Comment by mgorra** [comment]
Fixed this in conflictResolution by making a popup alert.
