### ISSUE TITLE
Removing (git rm) has/had threading issues

### ISSUE THREAD

**Issue by grenche** [dmusican/Elegit#619]
handleRemoveButton() in SessionController was threaded in the "old way" and I don't think it has really been tested because when called, asserts for being in the FX thread fail. Without spinning off a new thread it seems to work fine, but that could still use testing.

Currently, the threading code is commented out and it is accompanied with a TODO message. I don't think any multithreading is happening when that method is called anymore.

**Comment by dmusican** [comment]
Bugs #546 and #481 are also about remove; it makes sense to look at this all at the same time.

**Comment by dmusican** [comment]
Remove is fast enough that I'm just going to take the threading out. If someone finds a use case later on where it's slow and bothering someone, they can file that again as a later bug. I've made the fix already regarding the "are you sure" check in #546. The key remaining issue, which is the hard one, is #481 .
