### ISSUE TITLE
Detect when files move and put that in the working tree with `git status`

### ISSUE THREAD

**Issue by grahamearley** [dmusican/Elegit#67]
Other clients (like Sourcetree) indicate that a file changed location. Our client just commits it without telling you what happened.

**Comment by dmusican** [comment]
Look again and see what's going on.

**Comment by erictwalker18** [comment]
This is not what other clients do now at least. It is possible to tell with commandline and using some fancy commands, but tracking a 'moved' file is not exactly what Git is meant for: http://stackoverflow.com/questions/2314652/is-it-possible-to-move-rename-files-in-git-and-maintain-their-history. Closing for now...
