### ISSUE TITLE
Get icon integrated into app

### ISSUE THREAD

**Issue by grahamearley** [dmusican/Elegit#69]
The generic java icon is so boring (for exported .app file)

**Comment by dmusican** [comment]
Make an E in a colored box and make it icon.

**Comment by dmusican** [comment]
Graham made an icon, and it's in Slack, but I don't think it ever made it into Elegit. Get it in and test on all three OSes.

**Comment by dmusican** [comment]
Emphasize Linux in particular

**Comment by dmusican** [comment]
Some permissions thingy.... work with Kiley.... ask for help?

**Comment by dmusican** [comment]
Works we hear on Windows, not on Mac, Linux matters most right now, so try it and see if can fix if not working.

**Comment by connellyj** [comment]
Works on Windows and on Linux in the VM. Haven't tried mac.

**Comment by dmusican** [comment]
Done!!!

**Comment by dmusican** [comment]
Get icon fixed on Mac without breaking other OSes.

**Comment by dmusican** [comment]
Under Linux, when alt-tabbing, icon looks blurry. Not high enough resolution?

**Comment by dmusican** [comment]
Need to fix for actual install. Passing to Eric.

**Comment by erictwalker18** [comment]
Icon shows up via a78e4cb
