### ISSUE TITLE
Log Usage Data

### ISSUE THREAD

**Issue by kileymaki** [dmusican/Elegit#76]
Nail down exactly how we want to gather information, including what information we want to gather.

**Comment by dmusican** [comment]
Look heavily at BlueJ BlackBox project. SIGCSE 2013???

**Comment by dmusican** [comment]
Dave needs to make up his @!@#@? mind and pick a server location.

**Comment by dmusican** [comment]
A server is now established at elegit.mathcs.carleton.edu, which we all have access to. I'm going to wire elegit.org to there, but we can definitely start making progress with the former domain.
