### ISSUE TITLE
Strange errors with Dave's CS251 repo (SSH)

### ISSUE THREAD

**Issue by grahamearley** [dmusican/Elegit#83]
NullPointers, MissingObjects, etc.

**Comment by grahamearley** [comment]
Ah, it's SSH

**Comment by grahamearley** [comment]
See #38

**Comment by dmusican** [comment]
I'm going to take this. It might be low priority, but it's a good way to test against some of my repos, and for me to learn about what's going on.

**Comment by dmusican** [comment]
Ok, here's what needs to be done.

First: we need a way for the user to enter in ssh password info as an alternative login, or further alternatively, for the user to enter path for the private ssh key. The login dialog needs to modified to have a drop box changing type of info entered. Once done, the authentication needs to be modified [as described here](http://www.codeaffine.com/2014/12/09/jgit-authentication/). That modification will have to go everywhere authentication happens, which suggests that this code should be centralized if it can. For starters, work on the fetch() method in RepoHelper.java.

**Comment by dmusican** [comment]
This is a major subset of #38. Closing this in lieu of that issue.
