### ISSUE TITLE
Fix layout of Branch Manager window

### ISSUE THREAD

**Issue by grahamearley** [dmusican/Elegit#89]
* Merge X into Y button doesn't show special characters
* Separate merging and branching
* Fix layout!

**Comment by grahamearley** [comment]
Split this up into a better MVC pattern without really changing the layout, so these fixes should be easier

**Comment by grahamearley** [comment]
Other feedback from user study:
Add an "OK" button to close the window, instead of just the standard X at the top

**Comment by connellyj** [comment]
It doesn't really exist after 207ff6fb030999b66022ab31946fa2915e437eaa
