### ISSUE TITLE
Improve conflict resolution process

### ISSUE THREAD

**Issue by grahamearley** [dmusican/Elegit#96]
Checking the conflicting file and clicking `Commit` doesn't feel right. Feels like you're committing a conflicted file and making things worse.

**Comment by grahamearley** [comment]
see #60 #47 #18

**Comment by erictwalker18** [comment]
I think we're as good as we're going to get before we do too much that Git doesn't do. The conflicting goes away once you add a file, just like in command-line and there's a special monitor for checking if conflicting files are modified
