### ISSUE TITLE
Commit graph shapes aren't explained

### ISSUE THREAD

**Issue by grahamearley** [dmusican/Elegit#99]
Circle = untracked branch, square = normal, triangle = head. 

Explain what they mean. And maybe dashed lines too.

**Comment by dmusican** [comment]
At the same time, think about whether these are the right shapes. Or should they be icons? Are there psuedo-standards in the Git community?

Right now: square=std commits, circle=branch heads, triangles=branch heads (one is tracked in local and remote, and one isn't).

Also should ask: are there other criteria we should be using to have a different shape for?
